// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0

package db

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Password struct {
	ID                uuid.UUID      `json:"id"`
	UserUuid          uuid.NullUUID  `json:"user_uuid"`
	Site              string         `json:"site"`
	SiteUsername      sql.NullString `json:"site_username"`
	SiteEmail         sql.NullString `json:"site_email"`
	GeneratedPassword string         `json:"generated_password"`
	CreatedAt         time.Time      `json:"created_at"`
}

type User struct {
	ID               uuid.UUID     `json:"id"`
	Username         string        `json:"username"`
	HashedPassword   string        `json:"hashed_password"`
	UserinfoUuid     uuid.NullUUID `json:"userinfo_uuid"`
	PasswordChangeAt time.Time     `json:"password_change_at"`
	CreatedAt        time.Time     `json:"created_at"`
}

type Userinfo struct {
	ID          uuid.UUID      `json:"id"`
	FirstName   sql.NullString `json:"first_name"`
	LastName    sql.NullString `json:"last_name"`
	PhoneNumber sql.NullString `json:"phone_number"`
	Email       sql.NullString `json:"email"`
	CreatedAt   time.Time      `json:"created_at"`
}
