// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0
// source: userInfo.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createUserInfo = `-- name: CreateUserInfo :one
INSERT INTO userinfo (
    id,
    first_name,
    last_name,
    phone_number,
    email
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5
) RETURNING id, first_name, last_name, phone_number, email, created_at
`

type CreateUserInfoParams struct {
	ID          uuid.UUID      `json:"id"`
	FirstName   sql.NullString `json:"first_name"`
	LastName    sql.NullString `json:"last_name"`
	PhoneNumber sql.NullString `json:"phone_number"`
	Email       sql.NullString `json:"email"`
}

func (q *Queries) CreateUserInfo(ctx context.Context, arg CreateUserInfoParams) (Userinfo, error) {
	row := q.db.QueryRowContext(ctx, createUserInfo,
		arg.ID,
		arg.FirstName,
		arg.LastName,
		arg.PhoneNumber,
		arg.Email,
	)
	var i Userinfo
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.PhoneNumber,
		&i.Email,
		&i.CreatedAt,
	)
	return i, err
}
